[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ONTraC"
version = "0.0.4a1"
authors = [
  { name="Wen Wang", email="wwang.bio@gmail.com" },
  { name="Shiwei Zheng", email="swzheng29@gmail.com" },
  { name="Crystal Shin", email="sjcshin5040@gmail.com" },
  { name="Guo-Cheng Yuan", email="gcyuan@gmail.com" }
]
description = "A niche-centered, machine learning method for constructing spatially continuous trajectories"
readme = "README.md"
requires-python = ">=3.11"
keywords=[
    "deep-learning",
    "pytorch",
    "pytorch geometric",
    "trajectory inference",
    "spatial omics"
]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies=[
    "pyyaml==6.0.1",
    "pandas==2.2.1",
    "torch==2.2.1",
    "torch_geometric==2.5.0",
]

[project.urls]
Homepage = "https://github.com/gyuanlab/ONTraC"
Issues = "https://github.com/gyuanlab/ONTraC/issues"