[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ONTraC"
version = "0.0.1"
authors = [
  { name="Wen Wang", email="wwang.bio@gmail.com" },
  { name="Shiwei Zheng", email="swzheng29@gmail.com" },
  { name="Crystal Shin", email="sjcshin5040@gmail.com" },
  { name="Guo-cheng Yuan", email="gcyuan@gmail.com" }
]
description = "Draft package for ONTraC"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"